### PR TITLE
feat: expose whitelist prop

### PR DESCRIPTION
**Pull request by narehart**
Exposes `whiteList` prop from `react-focus-on` for cases where ref shards cannot be used, e.g., another library that renders a dropdown into the body.

### CODE REVIEW

**Comment by theKashey** [comment]
I should be wired to `ScrollLock` as well, or it will suppress events from "outer" nodes.
And right now it does not support such prop.

Would it be required to solve your case?

**Comment by narehart** [comment]
Not required in my case because there is no scrolling on the dropdowns being rendered. But I could see it being a problem.

**Comment by theKashey** [comment]
Ok. Let's solve one problem a time. 

I am also going to rename this prop as long as it's actually about `ignore`, however it will also require to "flip" the meaning of result

Like `shouldIgnore?: (activeElement: HTMLElement) => boolean;` -> true is "ignore", "false" is handle.
```diff
- <FocusOn whiteList={node => document.getElementById('root').contains(node)}>
+ <FocusOn shouldIgnore={node => !document.getElementById('root').contains(node)}>
```

Nowadays usually there are 2 props (in different tools, like Jest for example):
- `includePattern` - always required. And this is what old `whiteList` is.
- `excludePattern` or `ignorePattern`. And this is what new `shouldIgnore` might be

Which way sounds better for you?

**Comment by narehart** [comment]
I agree `shouldIgnore` makes more sense

**Comment by jacobweber** [comment]
BTW, this alternate name isn't documented -- I was trying to use whiteList.

**Pull request merged**
