### PR TITLE
Switch from click to mousedown (and touchend to touchstart) for click outside behaviour

### LINKED ISSUE #20: Click outside should be bound to mousedown / touchstart rather than click / touchend
Hi @theKashey,

After doing some research, I found another behaviour similar to the work we did on the escape key behaviour (#15).

Similarly here, looking at what the OS does for all types of modal layers (things like save system menus, app menus, right click menus, open selects, etc) click outside always executes instantly as soon as pressing down, on `mousedown` basically.

I believe we should also bind to `mousedown` rather than `click`?

Small change again, but I think offers much better consistency.
Let me know your thoughts, I'll send you a PR for it as well in a minute.

Cheers 👍

### PR DESCRIPTION
**Pull request by benoitgrelard**
Closes #20

### CODE REVIEW

**Comment by theKashey** [comment]
Makes sense from a consistency point of view. 
However, I haven't found any "system" `Modal` I could close by clicking outside - usually they ignore it.
However, "clicking" on a foreground window bring it to top on mouse down, not click.

**Comment by benoitgrelard** [comment]
Yeah exactly, it's less common in system dialogs to use click outside.
Good point on foreground window being on mouse down rather than click too though, seems to be consistent with the rest as I found.

Feel free to review #21 then, I think I tweaked everything necessary.

**Comment by theKashey** [comment]
Then let's move forward!

**Comment by benoitgrelard** [comment]
Awesome, let me know when you're able to release a new version with this change.

**Comment by theKashey** [comment]
Give me some time to check, as long as there is another _unpublished_, and yet untested change - #19

**Pull request merged**
